# Generated by Django 3.1.4 on 2020-12-30 02:26

import EShop.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent', models.DecimalField(decimal_places=5, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('gatewayResponseCode', models.CharField(max_length=5, null=True)),
                ('errorCode', models.CharField(max_length=3, null=True)),
                ('response', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage_type', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EshopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('deactivated', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(default=EShop.models.genrate_token, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(through='EShop.Item', to='EShop.Price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['massage_type', 'duration', 'start_date'], name='EShop_price_massage_9de790_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='EShop.purchase', to_field='token'),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='EShop.discount'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EShop.price'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EShop.purchase'),
        ),
        migrations.AddField(
            model_name='item',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code', 'end_date'], name='EShop_disco_code_ecc9a7_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='EShop.item'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['token'], name='EShop_purch_token_6436ac_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'timestamp'], name='EShop_purch_user_id_b62a84_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['orderId'], name='EShop_payme_orderId_aac8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['purchase'], name='EShop_item_purchas_8db840_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time'], name='EShop_booki_start_t_a53643_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['item', 'start_time'], name='EShop_booki_item_id_113d88_idx'),
        ),
    ]
