# Generated by Django 3.1.4 on 2020-12-30 02:27
from datetime import timedelta

from django.db import migrations

prices = {
   'Thai Massage': {
       30: 40,
       45: 55,
       60: 65,
       90: 95,
       120: 130
   },
   'Foot Massage': {
       30: 49,
       45: 59,
       60: 69,
       90: 99,
       120: 135
   },
   'Aroma Oil Massage': {
       30: 49,
       45: 69,
       60: 79,
       90: 120,
       120: 155
   },
   'Hot Stone Massage': {
       30: 55,
       45: 70,
       60: 95,
       90: 135,
       120: 170
   },
   'Deep Tissue Massage': {
       30: 60,
       45: 75,
       60: 95,
       90: 135,
       120: 175
   },
   'Remedial Massage': {
       30: 55,
       45: 70,
       60: 85,
       90: 135,
       120: 170
   },
   'Body Scrub': {
       30: 60,
       45: 75,
       60: 95,
       90: 135
   },
   'Facial Massage': {
       30: 50,
       45: 60,
       60: 80,
       90: 100
   },
}


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0001_create_tables'),
    ]

    def add_prices(apps, schema_editor):
        Price = apps.get_model('EShop', 'Price')
        for massage, pricing in prices.items():
            for duration, price in pricing.items():
                Price(
                    massage_type=massage,
                    duration=timedelta(minutes=duration),
                    price=price
                ).save()


    operations = [
        migrations.RunPython(add_prices)
    ]
