"""add payment table

Revision ID: a19bd69b5c89
Revises: 1f0a61db725e
Create Date: 2020-12-15 14:25:44.756362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a19bd69b5c89'
down_revision = '1f0a61db725e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('orderId', sa.String(), nullable=False),
    sa.Column('gatewayResponseCode', sa.String(length=2), nullable=True),
    sa.Column('errorCode', sa.String(length=3), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['sabai_thai.customer.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sabai_thai'
    )
    op.create_index('idx_orderId', 'payment', ['orderId'], unique=False, schema='sabai_thai')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orderId', table_name='payment', schema='sabai_thai')
    op.drop_table('payment', schema='sabai_thai')
