"""add tables with indices

Revision ID: f6d1cf333d74
Revises: 2e5c7c09f600
Create Date: 2020-12-14 16:59:08.293504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d1cf333d74'
down_revision = '2e5c7c09f600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=False),
    sa.Column('buyer_email', sa.String(), nullable=False),
    sa.Column('buyer_phone', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='sabai_thai'
    )
    op.create_index('idx_email_timestamp', 'customer', ['buyer_email', 'timestamp'], unique=False, schema='sabai_thai')
    op.create_index('idx_uuid', 'customer', ['uuid'], unique=False, schema='sabai_thai')
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('per_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percent', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sabai_thai'
    )
    op.create_index('idx_code_end_date', 'discount', ['code', 'end_date'], unique=False, schema='sabai_thai')
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('massage_type', sa.String(), nullable=False),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sabai_thai'
    )
    op.create_index('idx_type_duration_date', 'price', ['massage_type', 'duration', 'start_date'], unique=False, schema='sabai_thai')
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['sabai_thai.customer.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['sabai_thai.discount.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['sabai_thai.price.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sabai_thai'
    )
    op.create_index('idx_customer_id', 'purchase', ['customer_id'], unique=False, schema='sabai_thai')
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['sabai_thai.purchase.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sabai_thai'
    )
    op.create_index('idx_purchase_id_start_time', 'booking', ['purchase_id', 'start_time'], unique=False, schema='sabai_thai')
    op.create_index('idx_start_time', 'booking', ['start_time'], unique=False, schema='sabai_thai')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_start_time', table_name='booking', schema='sabai_thai')
    op.drop_index('idx_purchase_id_start_time', table_name='booking', schema='sabai_thai')
    op.drop_table('booking', schema='sabai_thai')
    op.drop_index('idx_customer_id', table_name='purchase', schema='sabai_thai')
    op.drop_table('purchase', schema='sabai_thai')
    op.drop_index('idx_type_duration_date', table_name='price', schema='sabai_thai')
    op.drop_table('price', schema='sabai_thai')
    op.drop_index('idx_code_end_date', table_name='discount', schema='sabai_thai')
    op.drop_table('discount', schema='sabai_thai')
    op.drop_index('idx_uuid', table_name='customer', schema='sabai_thai')
    op.drop_index('idx_email_timestamp', table_name='customer', schema='sabai_thai')
    op.drop_table('customer', schema='sabai_thai')
    # ### end Alembic commands ###
